version: v1-winbuild-{build}

image: Visual Studio 2019

platform:
  - Win32
  - x64

environment:
  vspath: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community'
  winflexbison: https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip

for:
-
  platform:
    only:
      - Win32
  environment:
    PATH: '%PATH%;C:\WinFlexBison;C:\Program Files (x86)\PostgreSQL\9.6\bin'
-
  platform:
    only:
      - x64
  environment:
    PATH: '%PATH%;C:\WinFlexBison;C:\Program Files\PostgreSQL\9.6\bin'

configuration:
  - Release
  
skip_commits:
  message: /workflows/
  files:
    - '.github/**'

install:
  - ps: Invoke-WebRequest -O winflexbison.zip $env:winflexbison
  - ps: Expand-Archive winflexbison.zip -Destination /WinFlexBison
  - ps: Copy-Item -Path /WinFlexBison/win_bison.exe /WinFlexBison/bison.exe
  - ps: Copy-Item -Path /WinFlexBison/win_flex.exe /WinFlexBison/flex.exe
  - ps: Invoke-WebRequest -Uri "https://get.enterprisedb.com/postgresql/postgresql-9.6.22-1-windows-binaries.zip" -Outfile /pgsql.zip
  - ps: Expand-Archive -Path /pgsql.zip -DestinationPath /
  - ps: New-Item -ItemType directory -Path "C:\Program Files (x86)\PostgreSQL"
  - ps: Move-Item -Path /pgsql -Destination "C:\Program Files (x86)\PostgreSQL\9.6"

before_build:
  - git clone --depth=1 https://github.com/calyptia/fluent-bit-ci.git ci
  - ps: Copy-Item -Path .\ci\scripts\run-unit-tests.ps1 .\ci\do-ut.ps1
  - if %PLATFORM%==Win32 call "%vspath%\VC\Auxiliary\Build\vcvars32.bat"
  - if %PLATFORM%==x64   call "%vspatH%\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - powershell ".\ci\do-ut.ps1;exit $LASTEXITCODE"
  - cd build
  - cpack

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: build/td-agent-bit-*.exe
    name: td-agent-bit
  - path: build/td-agent-bit-*.zip
    name: td-agent-bit-zip
